### ISSUE TITLE
Hoow can I instantiate THSegmentedPager in UIViewController?

### ISSUE THREAD

**Issue by afiq90** [hons82/THSegmentedPager#11]
How can I instantiate THSegmentedPager in Timeline.m(inherit from UIViewController) rather than AppDelegate.m?

What I mean is I wanna show THSegmentedPager when user open the Timeline View Controller instead of THSegmentedPager when load when user open the app. Thank you.

**Comment by hons82** [comment]
I'm not really sure what you're asking about. The example APP is just an example... you could even add a button with a segue and let that point to the THSegmentedPager.

Instantiate it in a UIViewController is kind of a Problem, as the pager itself is a UIViewController
```Objective-C
@interface THSegmentedPager : UIViewController<UIPageViewControllerDataSource,UIPageViewControllerDelegate>
```
so it would be a UIViewController in a UIViewController which makes only sense if you plan to push it on the Navigation stack or inside a ContainerView.

**Comment by afiq90** [comment]
if i want to put in containerview, how can i do that? sorry i'm novice. hope you can help me. thank you. :)

**Comment by hons82** [comment]
I'll create an example for that (but I don't know if I'll have time today)
Do u use
- Storyboard?
- Obj-C or Swift?

**Comment by afiq90** [comment]
sorry for late reply, I'm using storyboard and objective c. thank you.
