### ISSUE TITLE
Does it support Swift?

### ISSUE THREAD

**Issue by qx** [hons82/THSegmentedPager#14]
Could not cast value of type 'testTab.MyFavAllViewController' (0x10bf34030) to 'THSegmentedPager' (0x10bf33fd0).
  test in swift  get error

**Comment by hons82** [comment]
I've already used it in a Swift project... so it will work.
I've planed to create a sample project in Swift but due to time constraints I'll probably postpone it to september.
If you need help with this I'd need more info about what u try to do there
