### ISSUE TITLE
UIPageViewController navigates to wrong page with Scroll transition style

### ISSUE THREAD

**Issue by JaxGit** [hons82/THSegmentedPager#18]
In THSegmentedPagerExample,

Given the user has switched from page A to page B while skipping some pages (like from Page 1 to Page 3);
When user swipes backwards (like leftwards in this case);
Then user can only get back to the previous page (like Page 1) instead of the adjacent page (like Page 2).

**Comment by JaxGit** [comment]
Inspired from http://stackoverflow.com/questions/12939280/uipageviewcontroller-navigates-to-wrong-page-with-scroll-transition-style
I've create a pull request to fix this abnormal behaviour.

**Comment by hons82** [comment]
Actually I can't reproduce this behaviour on any of my Devices running iOS9

Later today when I'm in the office I'll check your pull and add it if its working for our Apps

**Comment by JaxGit** [comment]
Ah... sorry I forgot to mention the test environment. I've just checked again and it seems this bug only exist for iOS 7, and has been fixed by Apple since iOS 8. Please add marco as your wish to neglect this workaround for iOS 8 and above.
