### ISSUE TITLE
How to support lazy loading controller?

### ISSUE THREAD

**Issue by xhzengAIB** [hons82/THSegmentedPager#2]
@hons82 

Jack

**Comment by cerupcat** [comment]
Was this ever implemented?

**Comment by hons82** [comment]
I don't think so.
In my Apps I use it with quite thin viewdidload methods and do the real init in the viewwillappears

**Comment by cerupcat** [comment]
I see. I might fork and try a different method to load only the viewcontrollers needed (before, current, after).

**Comment by hons82** [comment]
That would be really nice.
If you have a solution for that I’d like to add it!

~Hannes
