### ISSUE TITLE
Reload Pager with new array

### ISSUE THREAD

**Issue by yashinbdas** [hons82/THSegmentedPager#22]
Hi,
Is it possible to reload the pager with a new array? I tried reloading the pager. It does not update the titles, unless i try swipe the pager. Once the pager reload, it allows the user only to scroll to 1 page that is adjacent to the selected page, even though there are more than 2 pages. But, once you click on any of the title tab, then it the pager works.

I'm checking this in iOS 7, iPad

**Comment by hons82** [comment]
No, currently not possible...
This would result in a complete repaint of the UI which in my case was never needed.

Could be a future enhancement, but its not planned yet
