### ISSUE TITLE
Disable page

### ISSUE THREAD

**Issue by suriksarkisyan** [hons82/THSegmentedPager#25]
Hi. I need to show few pages, but some of them should be disabled(no click, no swipe). I mean user cant get info from them. For example we had 3 pages. I should open second page at start and disable first and third .
Is it possible to disable one or few pages? It may be in future?

**Comment by hons82** [comment]
That's a bit problematic... lets say you have 5 pages
1 | 2 | 3 | 4 | 5
You are on 3 and now you disable 2 and 4... 
This would mean that I'd need to jump over them and show only 1 | 3 | 5

I'd need to check if PageViewControl allows that, and if the component I'm using for the header is allowing that. Currently I'm a bit short on time, as I'm working on new things, so I can't tell you now if it will ever be there.

However, if you'd like to work on it, and provide a PR, I'd consider adding it to the library

**Comment by suriksarkisyan** [comment]
Yes, not the simplest task. What about UIButton instead touches? This way you can just disable buttons and set another title color. Also you can disable swipe if any page is disabled and change pages only from button action.

Same with time for me, but i will try.

Hope this will be added in the future.

Thank you :)
