### ISSUE TITLE
Manual install

### ISSUE THREAD

**Issue by SolomonBier** [hons82/THSegmentedPager#4]
Having issues with:

HMSegmentedControl@hons82/HMSegmentedControl.h not found

Also pod install fails as well

**Comment by hons82** [comment]
Hi,
sorry I'd need more info on this. I've just run it using the example project and a project where I actually use this component and got no errors at all. This is using pod.

If you manually insert the files you need to be aware that it is based on [HMSegmentedControl@hons82](https://github.com/hons82/HMSegmentedControl) so you'll need to copy those files too and probably change the import declaration for them. 

Actually I should describe that process better in the readme, but I'm using it only on pods, so I was not aware of that

**Comment by SolomonBier** [comment]
Hons-let me try with HMSegmentedControl@hons82 , didn't realize that was needed !
